### ISSUE TITLE
Open Picker & Date Selection Bugs

### ISSUE THREAD

**Issue by gryevns** [haoxins/react-flatpickr#133]
https://codesandbox.io/s/react-example-forked-k2ukm?file=/index.js

First issue relates to toggling calendar visibility. There's a strange bug with my touchpad; if I tap the input then the calendar doesn't open, only when I hard click the input does it show.

Second issue can be seen if you click the input and attempt to select todays date. No value is set within the input field.

Note - rolling back to `3.10.4` resolves both of these issues.

**Comment by RafiqAli** [comment]
Same issue

**Comment by jacobmischka** [comment]
`3.10.4` and `3.10.6` are identical, the most recent release simply reverted bad behavior introduced in `3.10.5`. So if reverting to `3.10.4` fixes your issue then the issue likely lies elsewhere, probably in upstream flatpickr.

**Comment by jacobmischka** [comment]
This is pretty old now I'm aware, but can you try 3.10.7? It looks like there was indeed an issue with the 3.10.6 release (#148), despite the code being identical to 3.10.4. I think it must not have built correctly before being published or something.

I'm going to assume this is fixed in 3.10.7, but please write back if I'm wrong.
