### ISSUE TITLE
How to set localization globally

### ISSUE THREAD

**Issue by Ilkhom-S** [haoxins/react-flatpickr#182]
Hello,

When I use native flatpickr. I could use localization globally. But in react-flatpick i can't set globally. Can you help me. I'm using nesx.js

Thanks in advance

**Comment by ayberkbaytok** [comment]
+1, localization needs to be implemented.

**Comment by jacobmischka** [comment]
> +1, localization needs to be implemented.

PRs welcome.

**Comment by leandrovieiras** [comment]
Hi @jacobmischka ,
I created a [PR](https://github.com/haoxins/react-flatpickr/pull/189) with my implementation for localization.
Please, test it first and send our thoughts, ok?

Best Regards,
Leandro Vieiras

**Comment by jacobmischka** [comment]
You should be able to do this directly using `flatpickr` as normal, or by creating a wrapper component that adds the localization you want and using that instead of base `<Flatpickr />` (or by adding the localization in the options yourself as normal and not using a wrapper component).

Both are exampled here: https://codesandbox.io/s/solitary-field-5d7rjl?file=/src/App.js

**Comment by leandrovieiras** [comment]
I understand but why did you write this info now? This issue was open more than 10 days ago and because I sent a PR that was rejected you close this issue.
I think you can develop a good solution to use the locale globally.

**Comment by jacobmischka** [comment]
I closed this because I don't see a need to create additional custom logic in a component wrapper, it takes the same 3 lines of code that the vanilla version requires:

```js
import flatpickr from "flatpickr";
import locale from "flatpickr/dist/l10n/ja";

flatpickr.localize(locale.ja);
```
