### ISSUE TITLE
Can't change hours and minutes normally.

### ISSUE THREAD

**Issue by gercog1** [haoxins/react-flatpickr#62]
When i am changing month or PM/AM, it changes perfectly, but when i am trying to change hours and minutes it changes it +1 and closes calendar. How to fix?

**Comment by rorz** [comment]
Had the same issue and did some digging-around in the regular flatpickr repo and found this:
https://github.com/flatpickr/flatpickr/issues/1241

Is your problematic `<Flatpickr />` in a modal by any chance? Mine was, and I believe that's where the issue was coming from.

Following the advice in the linked issue thread, I added a `static: true` value to the options prop object, and also overrode the `.flatpickr-wrapper` class as follows:
```
.flatpickr-wrapper {
  position: absolute !important;
}
```

Works OK for me now :) Hope it helps

**Comment by miguelyoobic95** [comment]
I have the same issue here and the fix above didn't work for me. I also have flatpickr inside a modal, just a couple of weeks ago I did not have this issue but after changing my implementation to use shadow-dom I now get this behavior

**Comment by miguelyoobic95** [comment]
any updates on this issue ?

**Comment by bagaskarala** [comment]
add config
`static:true`
